# Welcome to Google Colab with github

In [17]:
import pandas as pd
import pandas as pd

employee = pd.DataFrame({
    "id": [1,2,3,4,5,6,7],
    "name": ["Joe","Henry","Sam","Max","Janet","Randy","Will"],
    "salary": [85000,80000,60000,90000,69000,85000,70000],
    "departmentId": [1,2,2,1,1,1,1]
})

department = pd.DataFrame({
    "id": [1,2],
    "name": ["IT","Sales"]
})

print(employee)
print(department)

   id   name  salary  departmentId
0   1    Joe   85000             1
1   2  Henry   80000             2
2   3    Sam   60000             2
3   4    Max   90000             1
4   5  Janet   69000             1
5   6  Randy   85000             1
6   7   Will   70000             1
   id   name
0   1     IT
1   2  Sales

In [22]:
df = pd.merge(
    employee,
    department,
    left_on="departmentId",
    right_on="id"
)
df.drop(
    columns=["id_x","id_y","departmentId"],
    inplace=True
)
df.rename(
    columns={
        "name_x":"Employee",
        "name_y":"Department",
        "salary":"Salary"
    },
    inplace=True
)
df = df[["Department", "Employee", "Salary"]]

df["rank"] = (
    df.groupby("Department")["Salary"]
      .rank(method="dense", ascending=False)
)

result = (
    df[df["rank"] <= 3]
    .drop(columns="rank")
    .reset_index(drop=True)
    .sort_values(by="Department",ascending=True)
)

result

  Department Employee  Salary
0         IT      Joe   85000
3         IT      Max   90000
4         IT    Randy   85000
5         IT     Will   70000
1      Sales    Henry   80000
2      Sales      Sam   60000

In [34]:
import pandas as pd

weather = pd.DataFrame({
    "id": [1, 2, 3, 4],
    "recordDate": [
        "2015-01-01",
        "2015-01-02",
        "2015-01-03",
        "2015-01-04"
    ],
    "temperature": [10, 25, 20, 30]
})

weather = weather.astype({
    "id": int,
    "temperature": int
})

weather["recordDate"] = pd.to_datetime(weather["recordDate"])

print(weather.dtypes)

id                      int64
recordDate     datetime64[ns]
temperature             int64
dtype: object

In [35]:
import pandas as pd

def rising_temperature(weather: pd.DataFrame) -> pd.DataFrame:
    weather = weather.sort_values("recordDate")

    return weather[
        (weather["recordDate"] - weather["recordDate"].shift(1)).dt.days.eq(1)
        & (weather["temperature"] > weather["temperature"].shift(1))
    ][["id"]]
rising_temperature(weather)

   id
1   2
3   4